---
title: "Azərbaycan dili - Oxu Savadlılığı Testi"
date: "17.01.2026"
output: word_document
---

**Sinif:** IV | **Müddət:** 40 dəqiqə

**Təşkilat:** ARTI

---

**Şagirdin adı, soyadı:** _______________________________________

**Sinif:** ______  **Məktəb:** ___________________________________

---


\newpage

# Mətn 1

## Azərbaycanın Böyük Şəhərləri və Onların Rəqəmli Xəritəsi

Azərbaycanın ən böyük şəhərlərini öyrənmək üçün rəqəmli texnologiyalar bizə kömək edir. GPS və peyk məlumatlarından istifadə edərək hazırlanmış bu cədvəl ölkəmizin şəhər inkişafını göstərir:

┌──────────────┬──────────┬─────────┬──────────┐
│ Şəhər        │ Əhali    │ Sahə    │ Yüksəklik│
├──────────────┼──────────┼─────────┼──────────┤
│ Bakı         │ 2.3 mln  │ 2140 km²│ -28 m    │
│ Gəncə        │ 335 min  │ 110 km² │ 400 m    │
│ Sumqayıt     │ 285 min  │ 83 km²  │ 1 m      │
│ Mingəçevir   │ 106 min  │ 130 km² │ 80 m     │
│ Şirvan       │ 85 min   │ 70 km²  │ 5 m      │
└──────────────┴──────────┴─────────┴──────────┘

Cədvələ diqqətlə baxsaq görərik ki, Bakı ən böyük şəhərdir və hətta dəniz səviyyəsindən aşağıda yerləşir. Gəncə dağlıq ərazidə qurulub, ona görə də yüksəkliyi çoxdur. Şirvan isə ən kiçik sahəyə malikdir. Rəqəmli cədvəllər şəhərlərimizi müqayisə etməyə, onların xüsusiyyətlərini anlamağa kömək edir. Bu məlumatlar planşetlərdə və smartfonlarda da əlçatandır.


## Suallar:


**Sual 1** (multiple_choice - 1 bal)

Cədvələ görə Azərbaycanın ən böyük şəhəri hansıdır?

- [ ] A. Bakı
- [ ] B. Gəncə
- [ ] C. Sumqayıt
- [ ] D. Mingəçevir


**Sual 2** (multiple_choice - 1 bal)

Gəncə şəhərinin əhalisi neçə min nəfərdir?

- [ ] A. 285 min
- [ ] B. 335 min
- [ ] C. 106 min
- [ ] D. 85 min


**Sual 3** (multiple_choice - 1 bal)

Şirvan şəhərinin sahəsi neçə km²-dir?

- [ ] A. 83 km²
- [ ] B. 130 km²
- [ ] C. 110 km²
- [ ] D. 70 km²


**Sual 4** (multiple_choice - 1 bal)

Bu cədvəli hazırlamaq üçün hansı texnologiyalardan istifadə edilib?

- [ ] A. Radio və televiziya
- [ ] B. GPS və peyk məlumatları
- [ ] C. Kitab və jurnallar
- [ ] D. Kompas və xəritə


**Sual 5** (multiple_choice - 1 bal)

Hansı şəhər ən yüksək yerdə yerləşir?

- [ ] A. Bakı
- [ ] B. Gəncə
- [ ] C. Sumqayıt
- [ ] D. Şirvan


**Sual 6** (short_response - 2 bal)

Nəyə görə Bakı şəhərinin yüksəkliyi mənfi göstərilir?


_Cavab:_






**Sual 7** (short_response - 2 bal)

Cədvələ baxaraq Mingəçevir və Sumqayıt şəhərlərinin sahəsini müqayisə et.


_Cavab:_






**Sual 8** (short_response - 2 bal)

Mətnə görə rəqəmli cədvəllərin bizə nə faydası var?


_Cavab:_






**Sual 9** (extended_response - 3 bal)

Sən bu məlumatları necə istifadə edərdin? Öz fikirlərini əsaslandır.


_Cavab:_






**Sual 10** (extended_response - 3 bal)

Bu cədvəldə hansı məlumat səndə ən çox maraq doğurdu və niyə?


_Cavab:_






\newpage

# Mətn 2

## Niyə Xəzər dənizi Azərbaycan üçün çox vacibdir?

Azərbaycanın şərqində yerləşən Xəzər dənizi ölkəmiz üçün çox vacib və dəyərlidir. Bu barədə müxtəlif arqumentlər var.

Birinci arqument: İqtisadi dəyər. Xəzər dənizində çox neft və qaz var. Bu sərvətlər Azərbaycanı zəngin edir və xalqımızın həyat səviyyəsini yüksəldir. Neft platformaları dənizdə işləyir və minlərlə insana iş verir.

İkinci arqument: Nəqliyyat yolu. Xəzər dənizi Azərbaycanı digər ölkələrlə birləşdirir. Bakı limanından gəmilər İran, Rusiya, Qazaxıstana gedir. Bu, ticarəti inkişaf etdirir və dostluq əlaqələrini möhkəmləndirir.

Üçüncü arqument: Turizm imkanları. Xəzər sahilində çoxlu otel, istirahət yeri var. İnsanlar üzməyə, balıq tutmaya gəlirlər. Bu da ölkəmizə gəlir gətirir.

Nəticə: Bütün bu arqumentlər göstərir ki, Xəzər dənizi Azərbaycan üçün həm iqtisadi, həm də mədəni baxımdan çox vacib bir sərvətdir. Ona qayğı ilə baxmalıyıq.


## Suallar:


**Sual 1** (multiple_choice - 1 bal)

Xəzər dənizi Azərbaycanın hansı tərəfində yerləşir?

- [ ] A. şərqində
- [ ] B. qərbində
- [ ] C. şimalında
- [ ] D. cənubunda


**Sual 2** (multiple_choice - 1 bal)

Mətnə görə, neft platformaları nə edir?

- [ ] A. balıq tutur
- [ ] B. minlərlə insana iş verir
- [ ] C. gəmi daşıyır
- [ ] D. turist gətirir


**Sual 3** (multiple_choice - 1 bal)

Bakı limanından gəmilər hansı ölkələrə gedir?

- [ ] A. Türkiyə, Gürcüstan, Ermənistan
- [ ] B. İran, Rusiya, Qazaxıstan
- [ ] C. Ukrayna, Belarus, Moldova
- [ ] D. Çin, Hindistan, Pakistan


**Sual 4** (multiple_choice - 1 bal)

İnsanlar Xəzər sahilində nə etmək üçün gəlirlər?

- [ ] A. neft çıxarmaq və ticarət etmək
- [ ] B. üzmək və balıq tutmaq
- [ ] C. gəmi tikməyə və təmir etməyə
- [ ] D. nəqliyyat yolları çəkməyə


**Sual 5** (multiple_choice - 1 bal)

Mətnə əsasən, Xəzər dənizinin nəqliyyat yolu olması hansı nəticəni verir?

- [ ] A. neft və qaz artır
- [ ] B. turizm azalır
- [ ] C. ticarət inkişaf edir və dostluq əlaqələri möhkəmlənir
- [ ] D. balıq tutmaq çətinləşir


**Sual 6** (short_response - 2 bal)

Niyə müəllif Xəzər dənizinin Azərbaycanı zəngin etdiyini yazır? Cavabınızı əsaslandırın.


_Cavab:_






**Sual 7** (short_response - 2 bal)

Turizm imkanlarının ölkəyə necə fayda verdiyini izah edin.


_Cavab:_






**Sual 8** (short_response - 2 bal)

Mətnin quruluşuna baxaraq, müəllifin arqumentlərini necə təşkil etdiyini göstərin.


_Cavab:_






**Sual 9** (extended_response - 3 bal)

Sizin fikrinizcə, Xəzər dənizi Azərbaycan üçün ən vacib hansı baxımdan faydalıdır? Öz cavabınızı mətnə əsaslanaraq əsaslandırın.


_Cavab:_






**Sual 10** (extended_response - 3 bal)

Mətnin sonunda "Ona qayğı ilə baxmalıyıq" cümləsinin mənasını izah edin və niyə bu vacib olduğunu əsaslandırın.


_Cavab:_






\newpage

# Mətn 3

## Qarabağ atlarının möhtəşəm dünyası

Qarabağ atları Azərbaycanın ən qiymətli xəzinəsidir. Bu möhtəşəm heyvanlar min illərdir ölkəmizin şərqindən qərbinə qədər yaşayır. Qarabağ atlarının ən maraqlı xüsusiyyəti onların metalik rəngləridir - qızılı, gümüşü və ya tunc rəngli tükləri günəş işığında parıldayır.

Bu atlar çox güclü və dayanıqlıdır. Onlar dağlıq ərazilərdə asanlıqla hərəkət edə bilir, sərt iqlim şəraitinə dözümlüdür. Qarabağ atları çox ağıllı və sahibinə sədaqətlidir. Keçmişdə bu atlar döyüşlərdə, ticarət yollarında və kənd təsərrüfatında geniş istifadə olunurdu.

Hazırda Qarabağ atları dünya çempionatlarında iştirak edir və ölkəmizin adını yüksəklərə qaldırır. Ağdam rayonundakı at təsərrüfatlarında bu nəcib heyvanlar qorunur və yetişdirilir. Qarabağ atları UNESCO tərəfindən dünya mədəni irsi kimi qeydə alınıb. Bu atların hər biri Azərbaycanın tarixi və mədəniyyətinin canlı simvoludur.


## Suallar:


**Sual 1** (multiple_choice - 1 bal)

Qarabağ atlarının ən maraqlı xüsusiyyəti nədir?

- [ ] A. Metalik rəngləri
- [ ] B. Böyük boyları
- [ ] C. Yüksək səsləri
- [ ] D. Tez qaçması


**Sual 2** (multiple_choice - 1 bal)

Qarabağ atları hansı təşkilat tərəfindən dünya mədəni irsi kimi qeydə alınıb?

- [ ] A. UNICEF
- [ ] B. UNESCO
- [ ] C. FIFA
- [ ] D. WHO


**Sual 3** (multiple_choice - 1 bal)

Qarabağ atları keçmişdə hansı sahələrdə istifadə olunurdu?

- [ ] A. Yalnız döyüşlərdə
- [ ] B. Yalnız kənd təsərrüfatında
- [ ] C. Döyüşlərdə, ticarət yollarında və kənd təsərrüfatında
- [ ] D. Yalnız yarışlarda


**Sual 4** (multiple_choice - 1 bal)

Qarabağ atları hazırda hansı rayondakı at təsərrüfatlarında yetişdirilir?

- [ ] A. Şuşa rayonunda
- [ ] B. Ağdam rayonunda
- [ ] C. Füzuli rayonunda
- [ ] D. Cəbrayıl rayonunda


**Sual 5** (multiple_choice - 1 bal)

Qarabağ atları niyə Azərbaycanın ən qiymətli xəzinəsi sayılır?

- [ ] A. Çox bahalı olduğu üçün
- [ ] B. Tarixi və mədəni əhəmiyyəti olduğu üçün
- [ ] C. Yalnız Azərbaycanda yaşadığı üçün
- [ ] D. Çox gözəl olduğu üçün


**Sual 6** (short_response - 2 bal)

Qarabağ atlarının tükləri niyə günəş işığında parıldayır?


_Cavab:_






**Sual 7** (short_response - 2 bal)

Qarabağ atlarının hansı xüsusiyyətləri onları dağlıq ərazilərdə yaşamağa uyğun edir?


_Cavab:_






**Sual 8** (short_response - 2 bal)

Mətnə əsasən, Qarabağ atlarının dünya çempionatlarında iştirakının Azərbaycan üçün əhəmiyyəti nədir?


_Cavab:_






**Sual 9** (extended_response - 3 bal)

Qarabağ atlarının Azərbaycanın tarixi və mədəniyyətinin simvolu olduğunu necə əsaslandırmaq olar? Mətnə əsaslanaraq izah edin.


_Cavab:_






**Sual 10** (extended_response - 3 bal)

Sizcə, Qarabağ atlarının qorunması nə dərəcədə vacibdir? Öz fikrinizi mətnə əsaslanaraq əsaslandırın.


_Cavab:_





